In [4]:
import numpy as np
import pandas as pd
scroes = np.random.randint(50,100,size=(50,5))
scores_df = pd.DataFrame(scroes,
             columns=['國文','數學','英文','地理','歷史'],
             index=range(1,51))
scores_df

    國文  數學  英文  地理  歷史
1   66  62  84  98  67
2   86  84  98  68  54
3   95  59  86  51  74
4   82  86  75  81  92
5   74  50  68  63  79
6   68  92  60  63  73
7   50  83  80  88  66
8   63  60  75  71  77
9   73  99  59  86  69
10  67  58  99  90  65
11  65  79  89  81  68
12  75  59  76  83  54
13  52  62  84  72  58
14  71  79  72  98  79
15  64  79  70  66  67
16  86  53  50  84  54
17  95  58  78  80  72
18  93  84  81  81  85
19  89  51  58  66  89
20  52  77  75  50  71
21  88  95  73  92  57
22  62  67  57  63  57
23  79  61  70  64  92
24  55  62  91  62  63
25  67  53  85  82  78
26  53  71  87  55  78
27  53  58  53  53  83
28  89  70  74  59  65
29  64  85  82  78  81
30  65  82  52  52  69
31  99  65  66  59  64
32  58  87  80  68  79
33  72  79  88  73  59
34  76  50  60  52  59
35  66  85  99  97  63
36  55  66  91  85  74
37  72  93  61  93  76
38  97  86  55  87  78
39  88  63  84  97  84
40  77  67  68  98  76
41  74  66  52  54  92
42  85  82  63  52  60
43  87  73  56  99  68
44  90  90  89  73  73
45  51  66  89  96  68
46  72  70  89  55  56
47  79  96  96  73  51
48  94  52  70  89  96
49  61  84  80  57  97
50  67  71  86  64  68

In [5]:
#'國文','數學','英文','地理','歷史'

scores_df['總分'] = scores_df['國文'] + scores_df['英文'] + scores_df['數學'] + scores_df['地理'] + scores_df['歷史']
scores_df['平均'] = scores_df['總分'] / 5
scores_df

    國文  數學  英文  地理  歷史   總分    平均
1   66  62  84  98  67  377  75.4
2   86  84  98  68  54  390  78.0
3   95  59  86  51  74  365  73.0
4   82  86  75  81  92  416  83.2
5   74  50  68  63  79  334  66.8
6   68  92  60  63  73  356  71.2
7   50  83  80  88  66  367  73.4
8   63  60  75  71  77  346  69.2
9   73  99  59  86  69  386  77.2
10  67  58  99  90  65  379  75.8
11  65  79  89  81  68  382  76.4
12  75  59  76  83  54  347  69.4
13  52  62  84  72  58  328  65.6
14  71  79  72  98  79  399  79.8
15  64  79  70  66  67  346  69.2
16  86  53  50  84  54  327  65.4
17  95  58  78  80  72  383  76.6
18  93  84  81  81  85  424  84.8
19  89  51  58  66  89  353  70.6
20  52  77  75  50  71  325  65.0
21  88  95  73  92  57  405  81.0
22  62  67  57  63  57  306  61.2
23  79  61  70  64  92  366  73.2
24  55  62  91  62  63  333  66.6
25  67  53  85  82  78  365  73.0
26  53  71  87  55  78  344  68.8
27  53  58  53  53  83  300  60.0
28  89  70  74  59  65  357  71.4
29  64  85  82  78  81  390  78.0
30  65  82  52  52  69  320  64.0
31  99  65  66  59  64  353  70.6
32  58  87  80  68  79  372  74.4
33  72  79  88  73  59  371  74.2
34  76  50  60  52  59  297  59.4
35  66  85  99  97  63  410  82.0
36  55  66  91  85  74  371  74.2
37  72  93  61  93  76  395  79.0
38  97  86  55  87  78  403  80.6
39  88  63  84  97  84  416  83.2
40  77  67  68  98  76  386  77.2
41  74  66  52  54  92  338  67.6
42  85  82  63  52  60  342  68.4
43  87  73  56  99  68  383  76.6
44  90  90  89  73  73  415  83.0
45  51  66  89  96  68  370  74.0
46  72  70  89  55  56  342  68.4
47  79  96  96  73  51  395  79.0
48  94  52  70  89  96  401  80.2
49  61  84  80  57  97  379  75.8
50  67  71  86  64  68  356  71.2

In [6]:
scores_df = pd.DataFrame(scroes,
             columns=['國文','數學','英文','地理','歷史'],
             index=range(1,51))
scores_df
sum_values = scores_df.sum(axis=1)
mean_values = scores_df.mean(axis=1)

In [7]:
scores_df['總分'] = sum_values
scores_df['平均'] = mean_values
scores_df

    國文  數學  英文  地理  歷史   總分    平均
1   66  62  84  98  67  377  75.4
2   86  84  98  68  54  390  78.0
3   95  59  86  51  74  365  73.0
4   82  86  75  81  92  416  83.2
5   74  50  68  63  79  334  66.8
6   68  92  60  63  73  356  71.2
7   50  83  80  88  66  367  73.4
8   63  60  75  71  77  346  69.2
9   73  99  59  86  69  386  77.2
10  67  58  99  90  65  379  75.8
11  65  79  89  81  68  382  76.4
12  75  59  76  83  54  347  69.4
13  52  62  84  72  58  328  65.6
14  71  79  72  98  79  399  79.8
15  64  79  70  66  67  346  69.2
16  86  53  50  84  54  327  65.4
17  95  58  78  80  72  383  76.6
18  93  84  81  81  85  424  84.8
19  89  51  58  66  89  353  70.6
20  52  77  75  50  71  325  65.0
21  88  95  73  92  57  405  81.0
22  62  67  57  63  57  306  61.2
23  79  61  70  64  92  366  73.2
24  55  62  91  62  63  333  66.6
25  67  53  85  82  78  365  73.0
26  53  71  87  55  78  344  68.8
27  53  58  53  53  83  300  60.0
28  89  70  74  59  65  357  71.4
29  64  85  82  78  81  390  78.0
30  65  82  52  52  69  320  64.0
31  99  65  66  59  64  353  70.6
32  58  87  80  68  79  372  74.4
33  72  79  88  73  59  371  74.2
34  76  50  60  52  59  297  59.4
35  66  85  99  97  63  410  82.0
36  55  66  91  85  74  371  74.2
37  72  93  61  93  76  395  79.0
38  97  86  55  87  78  403  80.6
39  88  63  84  97  84  416  83.2
40  77  67  68  98  76  386  77.2
41  74  66  52  54  92  338  67.6
42  85  82  63  52  60  342  68.4
43  87  73  56  99  68  383  76.6
44  90  90  89  73  73  415  83.0
45  51  66  89  96  68  370  74.0
46  72  70  89  55  56  342  68.4
47  79  96  96  73  51  395  79.0
48  94  52  70  89  96  401  80.2
49  61  84  80  57  97  379  75.8
50  67  71  86  64  68  356  71.2

In [8]:
scores_df.sort_values(by='總分',ascending=False).iloc[:5]

    國文  數學  英文  地理  歷史   總分    平均
18  93  84  81  81  85  424  84.8
4   82  86  75  81  92  416  83.2
39  88  63  84  97  84  416  83.2
44  90  90  89  73  73  415  83.0
35  66  85  99  97  63  410  82.0

In [9]:
#使用subscript[],過濾資料
scores_df[scores_df['平均'] < 80]

    國文  數學  英文  地理  歷史   總分    平均
1   66  62  84  98  67  377  75.4
2   86  84  98  68  54  390  78.0
3   95  59  86  51  74  365  73.0
5   74  50  68  63  79  334  66.8
6   68  92  60  63  73  356  71.2
7   50  83  80  88  66  367  73.4
8   63  60  75  71  77  346  69.2
9   73  99  59  86  69  386  77.2
10  67  58  99  90  65  379  75.8
11  65  79  89  81  68  382  76.4
12  75  59  76  83  54  347  69.4
13  52  62  84  72  58  328  65.6
14  71  79  72  98  79  399  79.8
15  64  79  70  66  67  346  69.2
16  86  53  50  84  54  327  65.4
17  95  58  78  80  72  383  76.6
19  89  51  58  66  89  353  70.6
20  52  77  75  50  71  325  65.0
22  62  67  57  63  57  306  61.2
23  79  61  70  64  92  366  73.2
24  55  62  91  62  63  333  66.6
25  67  53  85  82  78  365  73.0
26  53  71  87  55  78  344  68.8
27  53  58  53  53  83  300  60.0
28  89  70  74  59  65  357  71.4
29  64  85  82  78  81  390  78.0
30  65  82  52  52  69  320  64.0
31  99  65  66  59  64  353  70.6
32  58  87  80  68  79  372  74.4
33  72  79  88  73  59  371  74.2
34  76  50  60  52  59  297  59.4
36  55  66  91  85  74  371  74.2
37  72  93  61  93  76  395  79.0
40  77  67  68  98  76  386  77.2
41  74  66  52  54  92  338  67.6
42  85  82  63  52  60  342  68.4
43  87  73  56  99  68  383  76.6
45  51  66  89  96  68  370  74.0
46  72  70  89  55  56  342  68.4
47  79  96  96  73  51  395  79.0
49  61  84  80  57  97  379  75.8
50  67  71  86  64  68  356  71.2

In [12]:
#使用subscript[]的搜尋方式
#平均80以下,歷史不及格的
scores_df[(scores_df['平均'] < 80) & (scores_df['歷史'] < 60)]

    國文  數學  英文  地理  歷史   總分    平均
2   86  84  98  68  54  390  78.0
12  75  59  76  83  54  347  69.4
13  52  62  84  72  58  328  65.6
16  86  53  50  84  54  327  65.4
22  62  67  57  63  57  306  61.2
33  72  79  88  73  59  371  74.2
34  76  50  60  52  59  297  59.4
46  72  70  89  55  56  342  68.4
47  79  96  96  73  51  395  79.0

In [14]:
#使用query()的搜尋
scores_df.query('平均<80')

    國文  數學  英文  地理  歷史   總分    平均
1   66  62  84  98  67  377  75.4
2   86  84  98  68  54  390  78.0
3   95  59  86  51  74  365  73.0
5   74  50  68  63  79  334  66.8
6   68  92  60  63  73  356  71.2
7   50  83  80  88  66  367  73.4
8   63  60  75  71  77  346  69.2
9   73  99  59  86  69  386  77.2
10  67  58  99  90  65  379  75.8
11  65  79  89  81  68  382  76.4
12  75  59  76  83  54  347  69.4
13  52  62  84  72  58  328  65.6
14  71  79  72  98  79  399  79.8
15  64  79  70  66  67  346  69.2
16  86  53  50  84  54  327  65.4
17  95  58  78  80  72  383  76.6
19  89  51  58  66  89  353  70.6
20  52  77  75  50  71  325  65.0
22  62  67  57  63  57  306  61.2
23  79  61  70  64  92  366  73.2
24  55  62  91  62  63  333  66.6
25  67  53  85  82  78  365  73.0
26  53  71  87  55  78  344  68.8
27  53  58  53  53  83  300  60.0
28  89  70  74  59  65  357  71.4
29  64  85  82  78  81  390  78.0
30  65  82  52  52  69  320  64.0
31  99  65  66  59  64  353  70.6
32  58  87  80  68  79  372  74.4
33  72  79  88  73  59  371  74.2
34  76  50  60  52  59  297  59.4
36  55  66  91  85  74  371  74.2
37  72  93  61  93  76  395  79.0
40  77  67  68  98  76  386  77.2
41  74  66  52  54  92  338  67.6
42  85  82  63  52  60  342  68.4
43  87  73  56  99  68  383  76.6
45  51  66  89  96  68  370  74.0
46  72  70  89  55  56  342  68.4
47  79  96  96  73  51  395  79.0
49  61  84  80  57  97  379  75.8
50  67  71  86  64  68  356  71.2

In [13]:
scores_df.query('平均<80 and 歷史<60')

    國文  數學  英文  地理  歷史   總分    平均
2   86  84  98  68  54  390  78.0
12  75  59  76  83  54  347  69.4
13  52  62  84  72  58  328  65.6
16  86  53  50  84  54  327  65.4
22  62  67  57  63  57  306  61.2
33  72  79  88  73  59  371  74.2
34  76  50  60  52  59  297  59.4
46  72  70  89  55  56  342  68.4
47  79  96  96  73  51  395  79.0